// Generated by CoffeeScript 1.9.3
$(function() {
  $("#run_my_code").on('click', function() {
    var i, ref, ref1, results;
    results = [];
    for (i = ref = $("#first_num").val(), ref1 = $("#second_num").val(); ref <= ref1 ? i <= ref1 : i >= ref1; ref <= ref1 ? i++ : i--) {
      results.push($("<div>", {
        "class": 'alert alert-success',
        role: 'alert',
        text: $("#link1").val()
      }).appendTo("#output"));
    }
    return results;
  });
  $("#second_num").change(function() {
    return $(".alert-success").remove();
  });
  return $("#first_num").change(function() {
    return $(".alert-success").remove();
  });
});
