// Generated by CoffeeScript 1.9.3
$(function() {
  $("#run_my_code").on('click', function() {
    var i, person, ref, ref1, results;
    $("#output").html("");
    results = [];
    for (i = ref = parseInt($("#first_num").val()), ref1 = parseInt($("#second_num").val()); ref <= ref1 ? i <= ref1 : i >= ref1; ref <= ref1 ? i++ : i--) {
      person = null;
      switch ($("#dropdown option:selected").text()) {
        case "Taylor Swift":
          person = 'taylor_small.jpg';
          break;
        case "Kim Kardashian":
          person = 'kim_small.jpg';
          break;
        case "Love Emoji":
          person = 'LoveEmoji_small.png';
      }
      $("<img>", {
        src: "./images/" + person
      }).appendTo("#output");
      results.push(console.log($("#first_num").val()));
    }
    return results;
  });
  return $("#clear_pics").on('click', function() {
    return $("#output").html("");
  });
});
